#!/usr/bin/env python3
"""
Netgate Blocklist Downloader

Downloads and merges community blocklists into a single domain file
for use by the mitmproxy addon and dnsmasq.

Sources:
- EasyList (Adblock Plus format)
- Peter Lowe's ad server list
- Steven Black's hosts file
- OISD blocklist
"""

import re
import sys
import logging
import requests
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="[netgate-lists] %(message)s")
log = logging.getLogger(__name__)

OUTPUT_PATH = "/etc/netgate/blocklist-domains.txt"
DNS_HOSTS_PATH = "/etc/netgate/blocked-hosts"

# Community blocklist sources
SOURCES = [
    {
        "name": "Steven Black Hosts",
        "url": "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts",
        "format": "hosts",
    },
    {
        "name": "Peter Lowe's Ad List",
        "url": "https://pgl.yoyo.org/adservers/serverlist.php?hostformat=nohtml&showintro=0",
        "format": "plain",
    },
    {
        "name": "OISD Basic",
        "url": "https://abp.oisd.nl/basic/",
        "format": "adblock",
    },
    {
        "name": "AdGuard DNS Filter",
        "url": "https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt",
        "format": "adblock",
    },
]

# Domains to never block
BUILT_IN_WHITELIST = {
    "localhost",
    "localhost.localdomain",
    "local",
    "broadcasthost",
    "ip6-localhost",
    "ip6-loopback",
}


def download_list(url: str, timeout: int = 30) -> str:
    """Download a blocklist URL."""
    try:
        resp = requests.get(url, timeout=timeout)
        resp.raise_for_status()
        return resp.text
    except requests.RequestException as e:
        log.warning(f"Failed to download {url}: {e}")
        return ""


def parse_hosts_format(text: str) -> set[str]:
    """Parse hosts-file format (0.0.0.0 domain.com or 127.0.0.1 domain.com)."""
    domains = set()
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) >= 2 and parts[0] in ("0.0.0.0", "127.0.0.1"):
            domain = parts[1].lower()
            if "." in domain and domain not in BUILT_IN_WHITELIST:
                domains.add(domain)
    return domains


def parse_plain_format(text: str) -> set[str]:
    """Parse plain domain list (one per line)."""
    domains = set()
    for line in text.splitlines():
        line = line.strip().lower()
        if line and not line.startswith("#") and "." in line:
            domains.add(line)
    return domains


def parse_adblock_format(text: str) -> set[str]:
    """Parse Adblock Plus format - extract domain-blocking rules only."""
    domains = set()
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("!") or line.startswith("["):
            continue
        # Match: ||domain.com^ patterns
        match = re.match(r"^\|\|([a-z0-9._-]+)\^?\s*$", line, re.IGNORECASE)
        if match:
            domain = match.group(1).lower()
            if "." in domain:
                domains.add(domain)
    return domains


def update_blocklists() -> int:
    """Download all sources, merge, and write output files."""
    all_domains: set[str] = set()

    for source in SOURCES:
        log.info(f"Downloading: {source['name']}")
        text = download_list(source["url"])
        if not text:
            continue

        if source["format"] == "hosts":
            domains = parse_hosts_format(text)
        elif source["format"] == "plain":
            domains = parse_plain_format(text)
        elif source["format"] == "adblock":
            domains = parse_adblock_format(text)
        else:
            continue

        log.info(f"  → {len(domains)} domains")
        all_domains.update(domains)

    # Remove whitelisted
    all_domains -= BUILT_IN_WHITELIST

    # Load user whitelist
    whitelist_path = Path("/etc/netgate/whitelist-domains.txt")
    if whitelist_path.exists():
        user_whitelist = {
            line.strip().lower()
            for line in whitelist_path.read_text().splitlines()
            if line.strip() and not line.startswith("#")
        }
        all_domains -= user_whitelist

    log.info(f"Total unique domains: {len(all_domains)}")

    # Write domain list for mitmproxy
    output = Path(OUTPUT_PATH)
    output.parent.mkdir(parents=True, exist_ok=True)
    with open(output, "w") as f:
        f.write(f"# Netgate blocklist - {len(all_domains)} domains\n")
        f.write("# Auto-generated by update-lists.py\n")
        for domain in sorted(all_domains):
            f.write(domain + "\n")

    # Write hosts format for dnsmasq
    dns_output = Path(DNS_HOSTS_PATH)
    with open(dns_output, "w") as f:
        f.write(f"# Netgate DNS blocklist - {len(all_domains)} domains\n")
        for domain in sorted(all_domains):
            f.write(f"0.0.0.0 {domain}\n")

    log.info(f"Written to {OUTPUT_PATH} and {DNS_HOSTS_PATH}")
    return len(all_domains)


if __name__ == "__main__":
    count = update_blocklists()
    print(f"Done. {count} domains blocked.")
    sys.exit(0)
